### ISSUE TITLE
Vector tiles availability

### ISSUE THREAD

**Issue by y3nd** [OpenDEM/OpenDEMsearcher#1]
Hello,

Is there any possibility to download already processed vector tiles data ? As .zip or .mbtiles files ?

Thanks

**Comment by OpenDEM** [comment]
No, but it is easy to do yourself. Have  a look at https://github.com/OpenDEM/OpenDEMsearcher. If you need any support, please let me know.

**Comment by OpenDEM** [comment]
Unfortunately I have lost your mail for some inexplicable reason. Please write to me again.
